### PR TITLE
added sprite task and amended documentation and setup to accommodate

### PR DESCRIPTION
**Pull request by jjmu15**
Hi,

I've added the workflow for a sprite task which is included in the setup and workflow you've created. Won't require any additional setup from the user but provides a spriting method. What do you think?

### CODE REVIEW

**Comment by mattbanks** [comment]
I'm cool with adding this! Can you ammend the pull request to leave the browserSync proxy at local.dev? I'm personally dynamically replacing that in a site creation script.

**Comment by jjmu15** [comment]
Done. Totally forgot that I'd changed that. Thanks

**Comment by mattbanks** [comment]
Merged!

**Comment by jjmu15** [comment]
Awesome. I forgot to add myself as a contributer in the docs if you wouldn't mind adding me?

No big deal but it would be nice. lol.

Thanks for the merge ;)

**Comment by mattbanks** [comment]
Will do! I have a couple small tweaks I'm going to push up in the next day or so, so I'll add you in :)

**Pull request merged**
